### PR TITLE
Fix plugin display filter parsing and setting of viewport options #55

### PR DESCRIPTION
**Pull request by BigRoy**
This implements the `parse_view` method in such a way that any currently registered custom plugin shapes are also captured in the settings. Similarly when applying the setting when they are for a plugin display filter they will be assigned in that manner.

This makes it possible to include `gpuCacheDisplayFilter` like any of the other arguments of the viewport options and still apply it correctly. That way we avoid making an additional options dictionary or something nested even further.

I'm not sure how new the plugin display filter features are, but I noticed they weren't present in the 2011 help documents. So that might still need to be checked.

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks Roy, could you share a usage example of this fix?

**Comment by BigRoy** [comment]
Sure. Previously plugin display filters would always get disabled during capture and there was no way to enable that, for example the `gpuCacheDisplayFilter` that gets registered by the gpuCache plug-in.

Now when you're parsing a view (panel) this information will also get collected:

```python
panel = "modelPanel1"
options = capture.parse_view(panel)
```

With gpuCache enabled this would include the information of the `gpuCacheDisplayFilter`

```python
assert "gpuCacheDisplayFilter" in options["viewport_options"]
```

And similarly applying this option will ensure that value is set like that:

```python
capture.capture(**options)
```

To override it manually:

```python
options = dict()
options["viewport_options"] = dict()
options["viewport_options"]["gpuCacheDisplayFilter"] = True
capture.capture(**options)
```

**Comment by mottosso** [comment]
Perfect, thanks.

Which version(s) of Maya did you test this on?

**Comment by BigRoy** [comment]
2016 only! (Don't have access right now to older versions unfortunately)

**Pull request merged**
