### PR TITLE
Fix #69 and #70

### LINKED ISSUE #69: Missing some ViewportOptions keys
# Problem

Having a quick look over the documentation I noticed some visibility options for the viewport to be missing, specifically the `imagePlane`, `planes`, `controlVertices` and `hulls` arguments for the `modelEditor` command are lacking in the `ViewportOptions` dictionary.

I noticed the absence of some of these because image planes happened to be always visible instead of adhering to the settings when combined with a `parse_view()`.

> The "missing ones" mentioned here have been available since Maya 2014: http://download.autodesk.com/global/docs/maya2014/en_us/CommandsPython/modelEditor.html

> Note: In 2017 for example you also have `pluginShapes` argument which is not around back in 2014. I'm not sure how far we want to be backwards compatible, but adding in newer keys might hurt older versions.

Not having these keys in the `ViewportOptions` dictionary also means they won't be parsed correctly with `parse_view` or alike.

# Solution

For now I'd propose to _at least_ have all flags that were in Maya since 2014 (or whatever version we choose as oldest official supported) _or_ have the querying of applying happen in a _try-except_ fashion.

### PR DESCRIPTION
**Pull request by BigRoy**
Implement a fix for #69 and #70

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks Roy, could you version this up?

Which Maya's was this tested with?

**Comment by BigRoy** [comment]
Tested with _Maya 2016 Extension 1 + SP6_

**Comment by mottosso** [comment]
Thanks Roy!

**Comment by mottosso** [comment]
Was waiting to merge because I wanted to build a Travis test for it, to run it on multiple versions of Maya. But I got pulled away. Next time. For now, fingers crossed it doesn't break on versions pre-2016.

**Comment by BigRoy** [comment]
Sure. If anything comes up let's address it first thing.

**Pull request merged**
