### PR TITLE
Fix #74

### LINKED ISSUE #74: Workaround Maya error when using raw frame numbers with only start and end frame
# Problem

When using raw frame numbers with `maya.cmds.playblast` and only a start and end frame supplied instead of explicit frames Maya prints an error.

To reproduce:
```python
import maya.cmds as mc

mc.playblast(viewer=False, startTime=2, endTime=9, format="image", compression="png", rawFrameNumbers=True)
# Error: -rawFrameNumber option must be used with at least one -frame flag, ignoring -rawFrameNumber. # 
```

# Proposal

We can workaround this quirky behavior by making frames explicit when `raw_frame_numbers = True` and no `frames` are supplied:

```python
#pseudocode
    if raw_frame_numbers and frame is None:
        frame = range(int(start_frame), int(end_frame) + 1)
```

### PR DESCRIPTION
**Pull request by BigRoy**

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks Roy, could you tell me a little more about this flag?

> Playblast typically numbers its frames sequentially, starting at zero. This flag will override the default action and frames will be numbered using the actual frames specified by the -frame or -startFrame/-endFrame flags. - [Docs](http://help.autodesk.com/cloudhelp/2015/ENU/Maya-Tech-Docs/CommandsPython/playblast.html#flagrawFrameNumbers)

This is what I get from the docs. Does it apply only to image sequences? And do image sequences not usually take on the frame number? I don't understand. :(

**Comment by BigRoy** [comment]
> Does it apply only to image sequences? 

Yes. Only for output that results in separate files.

> And do image sequences not usually take on the frame number?

No. By default (with `raw_frame_numbers = False`) the output always starts the resulting filenames' frame numbers from zero counting upwards.

The difference would be:

```
# playblasting with raw frame numbers OFF starting playblast from frame 5.
test.0000.png
test.0001.png
test.0002.png
test.0003.png
...
# playblasting with raw frame numbers ON starting playblast from frame 5.
test.0005.png
test.0006.png
test.0007.png
test.0008.png
...
```

---

_Note: I just noticed there's a bug in maya when playblasting to an image sequence with raw frame numbers enabled when doing so for *negative frame ranges*. The frames will not be named correctly but will instead get the minimum integer as frame number, for example: `testa.-2147483648.png`  As such raw frame numbers cannot write out images for negative frames.

**Comment by mottosso** [comment]
Wow, I did not know that. I would have expected frames to always have their corresponding frame number.

What do you think about making this the default behaviour? Would it break things for those that depend on it? I think this would be the intuitive thing to do, but could be alone in that.

> I just noticed there's a bug 

Is this something we could wrap? By perhaps generating our own file name based on the frame numbers?

**Comment by mottosso** [comment]
Also, what if the frame number is higher than 10,000?

**Comment by aardschok** [comment]
The issue @BigRoy discussed in the note in his comment just got a bit more interesting, I will elaborate:

1. The time range I blasted was -50 to 200
2. Output was image sequence
3. The Raw Frame Numbers was checked

The image sequence got written out with a frame number but instead of the minimum integer as frame number, it got the frame number as -050. The file of frame -50 will be next to the file of frame 50:

This results in a mixed file sequence, this might be resolved to any other software which can read the files in the correct order.

```
# re-producable case
# playblast as image sequence
import maya.cmds as cmds

# create playblast from frame -10 to 10 with raw frame numbers
# results in correct file name per frame
cmds.playblast(filename="C:/a_raw_frame_numbers_start_end",
                     startTime=-10,
                     endTime=10,
                     rawFrameNumbers=True,
                     format="image",
                     compression="png")

 # create playblast from frames between -10 and 10 with raw frame numbers
 # results in correct file name for each positive frame, negative frame numbers 
 # get filename.-2147483648.png
cmds.playblast(filename="C:/b_raw_frame_numbers_frames",
                      frame=[float(x) for x in range(-10, 11)],
                      rawFrameNumbers=True,
                      format="image",
                      compression="png")

# create playblast from frames between -10 and 10 without raw frame numbers
# results in sequential file names starting from 0
cmds.playblast(filename="C:/d_frames",
                      frame=[float(x) for x in range(-10, 11)],
                      rawFrameNumbers=False,
                      format="image",
                      compression="png")
```

**Comment by BigRoy** [comment]
It's funny that the top example using only `startTime` and `endTime` actually works correctly for formatting but is the one that gives the error message as described in #74 

> Edit: When using frame 9990 to 10010 it gets automatically a five digit formatting ( ##### )

In this case only the numbers above 9.999 get 5 frame padding; those below the 10.000 mark do *not* automatically get it.

**Comment by BigRoy** [comment]
About that negative frame range bug in `maya.cmds.playblast`

> Is this something we could wrap? By perhaps generating our own file name based on the frame numbers?

I'm not sure how. Potentially what we could do is rename the files after the playblast but that means we'll get into a tricky situation, because the only way to playblast the files then is to do so by forcing the `raw_frame_numbers` to False and rename the files afterwards based on the (sorted; because Maya does that internally [according to the docs](http://download.autodesk.com/us/maya/2011help/CommandsPython/playblast.html#flagframe)) frames that were passed. Problem there is that if it's first playblasting to _non-raw frame numbers_ that it might overwrite other files starting at 0000, etc. So then we'll also need to define an intermediate file location.

@mottosso What were your thoughts on wrapping and fixing this?

**Comment by mottosso** [comment]
> What were your thoughts on wrapping and fixing this? Especially regarding how?

What kind of work do you think it would involve to take manual control over the image capturing and file-writing process?

```python
# E.g.
for frame in range(-50, 100):
  QtCore.grabWidget(viewport, "c:/destination/image.%04d.png" % frame)
```

**Comment by BigRoy** [comment]
I think using the grab widget method wouldn't preserve the possibility of playblasting offscreen, but I believe that are API methods that do allow to do so. I'm not sure how they compare in speed with the `playblast` command though. Didn't you test that some time ago? (I remember you were testing to capture four viewports at once)

**Comment by mottosso** [comment]
Doubt there'd be any concern on performance, what takes time is changing frame and writing to disk, `cmds.playblast` must do that too.

I did test that, https://github.com/mottosso/maya-multicapture/blob/master/multicapture.py

Undecided whether it's the best idea, but it'd open the doors to further manipulation, such as adding more elements to the captured images. Like asset and project information.

**Comment by BigRoy** [comment]
> Undecided whether it's the best idea, but it'd open the doors to further manipulation, such as adding more elements to the captured images. Like asset and project information.

Yes, maybe. But it would also become more involved to produce movies with specific encoding options, we'd then also need to hook up an encoder.

**Comment by mottosso** [comment]
Ok, let's keep it in the back of our minds. Should we merge #76 for now?

**Comment by BigRoy** [comment]
There's just one comment with review pending in #76 before we can merge. Once we have that approved or changed I guess we can merge that PR.

**Comment by mottosso** [comment]
Can we close this, or should we merge this too?

**Comment by BigRoy** [comment]
This should work perfect together with #76. Let's merge this too.

**Pull request merged**
