### PR TITLE
Implement #52

### PR DESCRIPTION
**Pull request by BigRoy**
Implement showOrnaments argument to disable HUD, axis icon and grid in playblast

### CODE REVIEW

**Comment by mottosso** [comment]
Could you also add a docstring for `sound`? Also, is sound not a boolean?

**Comment by mottosso** [comment]
Looks like `sound` is a string; the name of the sound node! Let's make the default value a `""` so it's clear what is expected.

- http://help.autodesk.com/cloudhelp/2015/ENU/Maya-Tech-Docs/CommandsPython/index.html

**Comment by BigRoy** [comment]
I tested some more. 

Whenever you pass the `sound` argument to `maya.cmds.playblast`, whether it's `None` or `""`, a warning message will spawn that it cannot find a valid sound file.

So we would have to wrap it up in kwargs to avoid that warning.

By the way, for future reference: to retrieve the currently active sound file:
```python
import maya.mel as mel
time_control = mel.eval("$gPlayBackSlider = $gPlayBackSlider")
sound = mc.timeControl(time, q=True, sound=True)
```

**Comment by BigRoy** [comment]
Should be fixed now. Let me know what you think.

**Comment by mottosso** [comment]
Looks good to me!

**Pull request merged**
