### PR TITLE
Add new capture() option to bypass the use of _independent_panel() which can cause crashes

### PR DESCRIPTION
**Pull request by darkvertex**
At the vfx studio where I work I found out that the use of an independent panel was causing freezes of Maya when playblasting with this module.

Regular playblasting worked without problems so it took me a while to narrow it down to and realise the throwaway panel being created in the `capture()` function was the culprit. I tried using the active panel and voila! no more freezing!

Knowing this, I decided to add the option of bypassing the use of the `_independent_panel()` contextmanager.

I feel the code is not super pretty and am open for alternative suggestions. I didn't like the idea of repeating the stuff in the main `with:` block two times so I went with this idea of a dummy contextmanager just returning the active panel. 

Do note that this as-is will not restore certain viewport settings, but that's why I have PR #85 for. (It would need to be merged before this one, technically speaking.)

### CODE REVIEW

**Comment by darkvertex** [comment]
Closing because I found the crashing came from elsewhere. Leaving the other PR since I believe it could be useful.

**Comment by BigRoy** [comment]
> Closing because I found the crashing came from elsewhere. Leaving the other PR since I believe it could be useful.

Anything interesting? ;) Good to hear you got it resolved.

**Comment by darkvertex** [comment]
Basically, the riggers at work were found to be using some Python DG nodes, and in Maya 2016 there seems to be a bug with Viewport 2.0 not wanting to playblast because it has to evaluate them but Python won't unlock so it just hangs.

**Comment by mottosso** [comment]
Try turning off Parallel Evaluation. It's the root of all evil.

**Pull request closed without merging**
