### PR TITLE
Maya 2017 compatibility

### PR DESCRIPTION
**Pull request by tokejepsen**
This makes capture compatible with Maya 2017 by using Qt.py for the Qt calls.

Sorry about the mixed changes to the code cosmetics. Might have had an OCD moment with PEP8.

### CODE REVIEW

**Comment by mottosso** [comment]
Neat. :)

I trust you've tested it and that it works. Pinging @BigRoy who is using it in production, would be fantastic to get you to beta-test this alongside Toke to make sure there aren't any rough edges.

**Comment by tokejepsen** [comment]
Testing it with https://github.com/BigRoy/maya-capture-gui as well :)

**Comment by BigRoy** [comment]
Great, I'll test this (maya 2016) tonight. Also, with the project layout changes (becoming a package now) we should update the README to reflect the new *usage* (installation) information.

**Comment by mottosso** [comment]
>becoming a package

Aah, I did not notice that. Yes this is a problem.

At the moment, it isn't a package at all, since the parent directory contains a symbol Python doesn't understand; a dash, `maya-capture`.

What would have to happen, is to put `capture.py` and `vendor/` into another subdirectory, and include a `__init__.py`.

However, I'm not entirely confident this is the right approach. Part of the appeal (at least to me) with this project is the single-file'nes of it. That I can copy/paste the contents of `capture.py` and run it successfully. Once it becomes a package, a world of opportunity opens up, including an invitation to complexity and feature bloat.

Sceptical, is what I am. I would rather bundle the contents of `Qt.py` within `capture.py`, and strip parts we don't need. Odds are we only need to remap `QtWidgets` and be done.

**Comment by tokejepsen** [comment]
We could also just to a simple try/except PySide2 then PySide?

**Comment by mottosso** [comment]
> We could also just to a simple try/except PySide2 then PySide?

Yeah, something along those lines would suffice I think.

**Comment by mottosso** [comment]
How is this coming along?

**Comment by tokejepsen** [comment]
Haven't looked at this yet. Unfortunately I don't have a lot of spare time atm.

**Comment by mottosso** [comment]
No worries.

"spare time". Is that Danish? Never heard of it!

**Comment by tokejepsen** [comment]
> "spare time". Is that Danish? Never heard of it!

Pretty sure it isn't; http://www.thefreedictionary.com/spare+time, but could be wrong :smile:

**Comment by BigRoy** [comment]
This should be as simple as:

```python
try:
    from PySide2 import QtGui, QtWidgets
except ImportError:
    from PySide import QtGui
    from PySide import QtGui as QtWidgets
```

Correct?

**Comment by mottosso** [comment]
I'd imagine so, yes.

**Comment by BigRoy** [comment]
> I'd imagine so, yes.

Seems to work flawlessly when also remapping the QApplication and QDesktopWidget to be in QtWidgets. (Tested in Maya 2016 and Maya 2017). Shall I commit this into #71 _or_ wait for the pull request to complete and then push this commit afterwards?

**Comment by mottosso** [comment]
QApplication is already in QtWidgets? :O

Let's make it a separate PR.

**Pull request closed without merging**
