### PR TITLE
Fix #33 and capture sound with parse_active_scene for #54

### LINKED ISSUE #33: Capturing brings up a viewport message regarding DOF
The new additions for options in #1 that got merged with #31 introduced a possible viewport message in Maya 2016 (when in-view messages are set as enabled). If disabled the in-view message is not shown.

Note that it's not a show-stopping issue. It's just somewhat odd behavior to see occur, as such it's good to discuss solutions.

### Problem

This behavior comes from the fact that `capture` now also applies default settings to the depth of field (disabling it) whereas before it ignored (or basically didn't know about) those settings.

Enabling/disabling this behavior is a matter of setting some `optionVar` settings:

```
optionVar -iv inViewMessageEnable false;control -edit -enable false prefsInViewMessageAssistEnable;control -edit -enable false prefsInViewMessageStatusEnable;control -edit -enable false prefsInViewMessageDisplayTime;control -edit -enable false prefsInViewMessageFontSize;control -edit -enable false prefsInViewMessageOpacity;
```

Above is the single line of MEL code Maya runs to disable the in-view messages.

### Solution

It would be a matter of adding another context manager that ensure the setting is temporarily disabled so these pop-ups do not occur.

### PR DESCRIPTION
**Pull request by BigRoy**
- Fix #33 where Maya 2016 would pop up an in-view message when the artist has that feature enabled (enabled by default in 2016)
- With the added support for the `sound` argument allow the parsing of the active sound with #54 with `parse_active_scene()`. It is important to note that since this requires the "sound" node to be in the scene to playblast correctly this might be somewhat unexpected when building *presets* as described in the `README.md`. When unavailable in the scene this would result in a warning message when playblasting.

For example:

```python
# say current scene has an active audio file
options = capture.parse_active_scene()
assert "sound" in options
assert options["sound"] is not None

# force create a new scene
maya.cmds.file(new=True, force=True)
capture.capture(**options)

# this would result in a warning about "missing sound file"
# since the new scene does not have a sound node
```

### CODE REVIEW

**Comment by mottosso** [comment]
Awesome! Feel free to merge when you're ready.

**Comment by BigRoy** [comment]
What do you think of the note regarding the `sound` argument when captured with `parse_active_scene`? Could this be problematic for some?

**Comment by mottosso** [comment]
Ah, couldn't the parse simply not include a sound argument if there isn't a sound node?

**Comment by BigRoy** [comment]
Ah, that's not the problem actually. It's the other way around. Say you'd parse the options when it has an audio file and use that setting in another scene where it doesn't have that audio node. It wouldn't error out, just have a warning message in the script editor. If `sound is None` it's not a problem.

**Comment by mottosso** [comment]
> Say you'd parse the options when it has an audio file and use that setting in another scene where it doesn't have that audio node.

I'm ok with that.

**Comment by BigRoy** [comment]
Great. Then it should work as is. I'll merge this now. 
Would you able to test this all soon in an older version of Maya (e.g. 2014 or 2015?)

**Comment by mottosso** [comment]
Yeah, I can do tomorrow.

**Pull request merged**
